name: "Stale PRs Finder"
description: "Find all of the stale PRs for a repo"
author: Charles Rumford
inputs:
  GITHUB_TOKEN:
    required: true
    description: The token to access the repo
  repo:
    required: false
    description: The repository to fetch the issues from
  days-since-created:
    required: false
    description: How many days have to pass to consider a pull request "stale"
    default: '1'
  ignoreDrafts:
    required: false
    description: If true, it ignore draft Pull Requests.
    default: true
  excludeLabels:
    required: false
    description: Set of labels which should be excluded from the search
    type: string
  requiredLabels:
    required: false
    description: Collections of labels separated by commas that should be required when searching for a PR.
    type: string
outputs:
  repo:
    description: 'The name of the repo in owner/repo pattern'
  data:
    description: 'A JSON object with the data'
  message:
    description: 'A markdown formatted message'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/tallwireless/github-stale-pr:latest'
